services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Paris
      - TZ=Europe/Paris
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      
      # Activation de l'Assistant IA
      - N8N_ENABLED_MODULES=instance-ai
      
      # Modèle DeepSeek via OpenRouter
      - N8N_INSTANCE_AI_MODEL=custom/deepseek-v4-pro
      - N8N_INSTANCE_AI_MODEL_URL=https://api.deepseek.com/v1
      - N8N_INSTANCE_AI_MODEL_API_KEY=${DEEPSEEK_API_KEY}
      
      # Sandbox Daytona (obligatoire)
      - N8N_INSTANCE_AI_SANDBOX_ENABLED=true
      - N8N_INSTANCE_AI_SANDBOX_PROVIDER=daytona
      - N8N_INSTANCE_AI_SANDBOX_IMAGE=daytonaio/sandbox:0.5.3-slim
      - N8N_INSTANCE_AI_SANDBOX_OVERRIDE=true
      - DAYTONA_API_URL=https://app.daytona.io/api
      - DAYTONA_API_KEY=${DAYTONA_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
